A cleaner merge of my changes
Thorfusion/Mekanism-Community-Edition pull request #36
Opened 2022-09-11 17:46 UTC by DrParadox7

Use this instead of #35

2022-09-11 17:49 UTC, maggi373 commented
it fails dude

2022-09-11 17:50 UTC, maggi373 commented
a shit maven is down

2022-09-11 17:57 UTC, maggi373 commented
you need to fix the error when compiling

2022-09-11 18:02 UTC, DrParadox7 commented
Alright. Fixed the sneaking lack of ";" and now it builds.

2022-09-11 18:04 UTC, DrParadox7 commented
These commits do not include anything that can now be done with Minetweaker _(such as the steel manufacturing from Metallurgic Infuser)_ since you fixed that.

2022-09-12 22:44 UTC, maggi373 requested changes
gemdiamond compat needs to be removed as its already implemented from terralizationcompat

2022-09-12 22:44 UTC, maggi373 commented on src/main/java/mekanism/common/integration/OreDictManager.java
> +		for(ItemStack ore : OreDictionary.getOres("gemDiamond"))
gemDiamond compat for enrichment chamber needs to be removed as its already implemented from terralizationcompat further down.

2022-09-13 14:43 UTC, maggi373 approved these changes

2022-09-13 14:44 UTC, merged